AWSTemplateFormatVersion: 2010-09-09

Description:
  This template deploys a mysql database

Parameters:
  GroupIdForDBs:
    Description: An environment name that is prefixed to resource names
    Type: String
  databasesubnet1:
    Description: An environment name that is prefixed to resource names
    Type: String
  databasesubnet2:
    Description: An environment name that is prefixed to resource names
    Type: String


Resources:
  Database:
    Type: AWS::RDS::DBInstance
    Properties:
      VPCSecurityGroups: 
       - !Ref GroupIdForDBs
      AllocatedStorage: '20'
      PubliclyAccessible: 'false'
      DBInstanceClass: db.t2.micro
      Engine: MySQL
      MasterUsername: performance
      MasterUserPassword: improvement
      DBSubnetGroupName: !Ref DatabaseSubnetGroup
      AvailabilityZone: us-east-1a


  DatabaseSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: subnet group
      SubnetIds: 
       - !Ref databasesubnet1
       - !Ref databasesubnet2