AWSTemplateFormatVersion: 2010-09-09

Description:
  This template deploys two ec2 instances

Parameters:
  GroupId:
    Description: An environment name that is prefixed to resource names
    Type: CommaDelimitedList
  WebSubnet1:
    Description: An environment name that is prefixed to resource names
    Type: String
  WebSubnet2:
    Description: An environment name that is prefixed to resource names
    Type: String

Resources:
  INSTANCE1:
    Type: AWS::EC2::Instance
    Properties: 
      ImageId: ami-02b972fec07f1e659
      SecurityGroupIds: !Ref GroupId
      InstanceType: t2.micro
      SubnetId: !Ref WebSubnet1
      UserData:
         Fn::Base64: |
            #!/bin/bash
            yum update -y
            yum install -y httpd.x86_64
            systemctl start httpd.service
            systemctl enable httpd.service
            echo "Hello World from $(hostname -f)" > /var/www/html/index.html


  INSTANCE2:
    Type: AWS::EC2::Instance
    Properties: 
      ImageId: ami-02b972fec07f1e659
      SecurityGroupIds: !Ref GroupId
      InstanceType: t2.micro
      SubnetId: !Ref WebSubnet2
      UserData:
         Fn::Base64: |
            #!/bin/bash
            yum update -y
            yum install -y httpd.x86_64
            systemctl start httpd.service
            systemctl enable httpd.service
            echo "Hello World from $(hostname -f)" > /var/www/html/index.html

Outputs:
  Webserver1:
    Value: !Ref INSTANCE1
    Export:
      Name: webserver1

  Webserver2:
    Value: !Ref INSTANCE2
    Export:
      Name: webserver2