AWSTemplateFormatVersion: 2010-09-09

Description:
  This template deploys two ec2 instances

Parameters:
  VPCID:
    Description: An environment name that is prefixed to resource names
    Type: String
  GroupIdLB:
    Description: An environment name that is prefixed to resource names
    Type: String
  WebSubnet1:
    Description: An environment name that is prefixed to resource names
    Type: String
  WebSubnet2:
    Description: An environment name that is prefixed to resource names
    Type: String
  Webserver1:
    Description: An environment name that is prefixed to resource names
    Type: String
  Webserver2:
    Description: An environment name that is prefixed to resource names
    Type: String

Resources:
  LoadBalancer:
    Type: "AWS::ElasticLoadBalancingV2::LoadBalancer"
    Properties:
      Subnets: 
       - !Ref WebSubnet1
       - !Ref WebSubnet2
      SecurityGroups: 
       - !Ref GroupIdLB

  TargetGroup:
    Type: "AWS::ElasticLoadBalancingV2::TargetGroup"
    Properties:
      HealthCheckIntervalSeconds: 30
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2
      Port: 80
      Protocol: HTTP
      UnhealthyThresholdCount: 5
      VpcId: !Ref VPCID
      Targets:
        - Id: !Ref Webserver1
          Port: 80
        - Id: !Ref Webserver2
          Port: 80
      TargetType: instance

  Listener:
    Type: "AWS::ElasticLoadBalancingV2::Listener"
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroup
      LoadBalancerArn: !Ref LoadBalancer
      Port: "80"
      Protocol: HTTP
      






